import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Login & Register',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {' '}
        <header className='mx-auto my-10 w-1/2'>
          <div className='options-container flex gap-5'>
            <Link
              href='/'
              className='underline'
            >
              Home
            </Link>
            <Link
              href='/register'
              className='underline'
            >
              Register
            </Link>
            <Link
              href='/login'
              className='underline'
            >
              Login
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
