import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import Image from 'next/image'
import homeIcon from '@/assets/home.svg'
import loginIcon from '@/assets/login.svg'
import signUpIcon from '@/assets/signUp.svg'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Login & Register',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {' '}
        <header className='mx-auto my-10 w-1/2'>
          <div className='options-container flex justify-between'>
            <Link href='/' className='underline flex gap-1'>
              <Image src={homeIcon} alt='Home icon' /> Home
            </Link>
            <Link href='/register' className='underline flex gap-1'>
              <Image src={signUpIcon} alt='Register icon' />
              Register
            </Link>
            <Link href='/login' className='underline flex gap-1'>
              <Image src={loginIcon} alt='Login icon' />
              Login
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
